### ISSUE TITLE
Initialize a new branch for a new UX

### ISSUE THREAD

**Issue by lbroudoux** [microcks/hub.microcks.io#17]
We'd like to test new UX frontend for Hub with modern techno and ability to be reused as a web component.
* Initialize a `new-ux` branch
* Update server backend dependencies to latest versions
* Do some house-keeping by updating the license headers

**Comment by soGit** [comment]
Hello @lbroudoux, I like your idea to start from hub.microcks.io
I propose to focus on the Frontend folder first (because the main point is to develop an migration approach for Microck's FrontEnd related projects). To move iteratively, let start with updating dependencies to the lates minor versions (check PR https://github.com/microcks/hub.microcks.io/pull/24 )
after that, I want to introduce "prettier" so, we have consistently formatted code across the project.
Along that we need to define the core functionality, so hight level e2e test can be created to avoid manual checks and simplify refactoring. https://playwright.dev/ can be used.
After that, migrate to the latest angular. If any lib(s) is not supported (migrate to https://shoelace.style/ or https://material.angular.io/components/categories).

Once we are up to date, we might switch to https://astro.build/ because hub.microcks.io has a mostly static content, that can be prerendered. 

What to you think?
